# Generated by Django 5.2.4 on 2026-01-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('product', 'Product Information'), ('order', 'Order Status'), ('shipping', 'Shipping & Delivery'), ('returns', 'Returns & Refunds'), ('technical', 'Technical Support'), ('partnership', 'Partnership'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('newsletter_subscribed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
